### PR TITLE
FEAT: test action scripts using testing actions

### PR DESCRIPTION
**Pull request by jorgepiloto**
This pull-request introduces a testing job in the CI. It allows to test the different scripts collected in the `scripts/` directory using the actions implemented in #42. This also has the advantage of testing the action itself.

### CODE REVIEW

**Comment by jorgepiloto** [comment]
I really like the new script for updating the `versions.json` fie ❤️

**Comment by jorgepiloto** [comment]
Still looking for a way to test this within our actions. The problem is that this is not a package but a script.

**Review by RobPasMue — APPROVED** [review]
LGTM! Just did a minor change in one of the files since Vale was complaining

**Comment by jorgepiloto** [comment]
Let me add one last change that @Revathyvenugopal162 asked for some days ago. That is having a "(stable)" not after the last stable release.

**Comment by jorgepiloto** [comment]
Great! Now the script is able to add the `X.Y (stable)` tag to the latest stable release in the project in a dynamic way.

**Pull request merged**
