### PR TITLE
fix: versions page generation

### LINKED ISSUE #252: Versions page not overriding all article content
🐞 **Problem**
The logic merged in #218 and #251 is working but needs to override the whole page content, see [https://actions.docs.pyansys.com/version](https://actions.docs.pyansys.com/version).

### PR DESCRIPTION
**Pull request by jorgepiloto**
Fix #252.

This pull-request guarantees that the content inside of the desired HTML tag gets override in favor of the Versions page. It also makes sure that the URL are actual HTML links by using the `<a>` tag.

I must confess I am not satisfied with this implementation. The reason is that, so far, multi-version documentation is "agnostic" to the theme you are using. That is why we need to accept this HTML tag to exactly now which is the element containing the main information of the page.

Use the following script and HTML file to reproduce locally. Feel free to modify the unique HTML tag containing the main info of the page to see how this works.

```bash
#!/bin/bash

html_file="index.html"
html_tag="section"
cname="cname.com"
tmp_file="temp.html" # Add variable for temporary file

# Create an array of folder names
folders=(*/)
folders=("${folders[@]%/}")

# Get the absolute path of the current directory
abs_path=$(pwd)

# Start building the HTML table
table="<table class=\"table\"><thead><tr><th>Version</th><th>URL</th></tr></thead><tbody>"

# Loop through the folder array and add each folder name and URL to the table
for folder in "${folders[@]}"; do
  url="https://$cname/version/${folder}"
  table+="<tr><td>${folder}</td><td><a href=\"${url}\">${url}</a></td></tr>" # Fix quotes
done

# Close the table
table+="</tbody></table>"

# Add a paragraph describing the table
paragraph="<p>This table lists all versions released for the project:</p>"

# Convert the HTML into a temporary one-line document so 'sed' works as
# desired
tr -d '\n\r' < "$html_file" > "$tmp_file" # Fix quotes

# Retrieve the open and closing tags for the desired element
input_tag="$html_tag" # Fix quotes
#close_tag=$(grep -o "<$input_tag\b[^>]*>" "$tmp_file" | sed "s|<$input_tag\([^>]*\)>|\1|") # Fix quotes and sed command
#close_tag=$(grep -o '<'$input_tag'\b[^>]*>' $tmp_file | sed 's/<'$input_tag'\( [^>]*)\(.*\)>/\1>/')
#close_tag=$(grep -o '<'$input_tag'\b[^>]*>' $tmp_file | sed 's/<'$input_tag'\([^>]*\)>.*/\1/')
close_tag=$(grep -o "<$input_tag\b[^>]*>" "$tmp_file" | sed 's/^<\([[:alnum:]]\{1,\}\)[^>]*>/<\/\1>/g')
open_tag=$(grep -o "<$html_tag\b[^>]*>" "$tmp_file")

echo "Input tag: $input_tag"
echo "Open tag: $open_tag"
echo "Close tag: $close_tag"

# Update the content of the page with the versions
sed -i "s|$open_tag.*$close_tag|$open_tag<h1>Versions</h1>$close_tag$paragraph$table|g" "$tmp_file" # Fix quotes and add variables

# Restore the style of the HTML file
tidy -q -indent -ashtml -o "$html_file" "$tmp_file" # Fix quotes and add variables

# Remove the temporary file
rm "$tmp_file"
```

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
      <section class="bd-article" role="main">
          OLD CONTENT
      </section>
    </body>
</html>
```

### CODE REVIEW

**Comment by RobPasMue** [comment]
I'll try to revie asap, thanks @jorgepiloto

**Comment by jorgepiloto** [comment]
@Revathyvenugopal162 suggested the approach of injecting a small script in the `footer`. This simplifies lots of things as long as the page has a footer. If there is no footer, we can inject the content in the header. Even with that, users still need to input the name of the unique HTML tag with the content.

**Review by RobPasMue — APPROVED** [review]
LGTM! Great bash scripts

**Comment by jorgepiloto** [comment]
Let's merge this just to confirm that it is a valid approach so at least we fix the bug. Later, we can work on the approach suggested by @Revathyvenugopal162.

**Pull request merged**
